version: "3"
services:
  node-app-login:
    container_name: node-login
    image: iulianroman/node-login:latest
    tty: true
    environment:
      - DBHOST=${DBHOST}
      - APPPORT=${APPPORT}
    restart: always
    ports:
      - "${APPPORT}:${APPPORT}"
    depends_on: 
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - "27017:27017"
