apiVersion: v1
kind: Pod
metadata:
  name: node-login-app
spec:
  containers:
  - name: login-app
    image: iulianroman/node-login
    env: 
    - name: APPPORT
      value: "8000"
    - name: DBHOST
      value: localhost
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
  - image: mongo
    name: mongodb
    ports:
    - containerPort: 27017
      protocol: TCP
